"""Export ONE year of registrations as a self-contained, gzipped SQL patch.

For moving a repaired year to another machine. A full pg_dump of this
database is 235MB; a single year is ~9MB gzipped, because a year is roughly
1.2M of 21M rows and the dump's bulk is indexes and the other years. After a
re-scrape repairs year N, this ships only year N.

The output is applied with psql: no pg_restore, no matching PostgreSQL major
version, and no separate delete step -- it carries its own DELETE inside a
transaction, so applying it twice is identical to applying it once:

    gunzip -c registrations-2023.sql.gz | psql -U vahan -d vahan

or, against the Docker stack:

    gunzip -c registrations-2023.sql.gz | \
      docker compose -f docker/docker-compose.yml exec -T postgres psql -U vahan -d vahan

`id` is deliberately omitted from the column list so the target assigns its
own -- ids differ between machines and mean nothing outside their own
database.

Usage: python -m app.scripts.export_year_delta --year 2023 [--out FILE]
"""
import argparse
import asyncio
import gzip
from pathlib import Path

from sqlalchemy.ext.asyncio import create_async_engine

from app.core.config import settings

# Every column except the surrogate id.
COLUMNS = (
    "state_code, state_name, rto_code, rto_name, year, month, maker, "
    "vehicle_class, vehicle_category, commercial_tier, fuel_type, "
    "vehicle_model, is_supplementary, count, recorded_at"
)


def _csv(value) -> str:
    """Field encoding matching COPY ... WITH (FORMAT csv).

    NULL is an UNQUOTED empty field; a genuine empty string is a QUOTED one
    ("").  That quoting is the only thing distinguishing them on import, and
    this schema depends on the difference: the natural-key index is built on
    COALESCE(maker,'') / COALESCE(fuel_type,''), and the scraper can persist
    an empty-string label from a malformed row. Emitting both unquoted turned
    a real '' into NULL on the target, which silently moves a row between
    scrape passes -- and a row-count check cannot see it, only content can.
    """
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    text_value = str(value)
    if text_value == "" or any(c in text_value for c in ',"\n\r'):
        return '"' + text_value.replace('"', '""') + '"'
    return text_value


async def main(year: int, out: Path) -> None:
    engine = create_async_engine(settings.DATABASE_URL)
    out.parent.mkdir(parents=True, exist_ok=True)

    rows = 0
    with gzip.open(out, "wt", encoding="utf-8", newline="") as fh:
        fh.write("-- Generated by app.scripts.export_year_delta\n")
        fh.write(f"-- registrations, year {year}\n")
        fh.write("BEGIN;\n")
        # Scoped to the year, so every other year on the target is untouched.
        fh.write(f"DELETE FROM registrations WHERE year = {year};\n")
        fh.write(f"COPY registrations ({COLUMNS}) FROM stdin WITH (FORMAT csv);\n")

        async with engine.connect() as conn:
            raw = await conn.get_raw_connection()
            asyncpg_conn = raw.driver_connection
            # Server-side cursor: streams 1.2M rows instead of materialising
            # them, so memory stays flat regardless of the year's size.
            async with asyncpg_conn.transaction():
                async for record in asyncpg_conn.cursor(
                    f"SELECT {COLUMNS} FROM registrations WHERE year = $1", year
                ):
                    fh.write(",".join(_csv(v) for v in record.values()) + "\n")
                    rows += 1

        fh.write("\\.\n")
        fh.write("COMMIT;\n")

    await engine.dispose()
    print(f"{rows:,} rows -> {out}  ({out.stat().st_size / 1_048_576:.1f} MB gzipped)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--year", type=int, required=True)
    parser.add_argument("--out", type=Path, default=None)
    args = parser.parse_args()
    asyncio.run(main(args.year, args.out or Path(f"registrations-{args.year}.sql.gz")))
